name: CPO_env
channels:
  - defaults
  - conda-forge
  - fastai
  - pytorch
dependencies:
  - python=3.11
  - numpy
  - pandas
  - scipy
  - pip
  - opencv
  - kaggle
  - pillow
  - fastai
  - mediapipe
  - matplotlib
  - seaborn
  - scikit-learn
  - torchvision
  - torchaudio
  - pip:
    - fastai
    - mediapipe
    - torch==2.6.0+cu126
    - torchvision
    - torchaudio
    - --extra-index-url https://download.pytorch.org/whl/cu126
